-- V1__init.sql — initial Pokédex schema (US03 persistence + auth users).
-- Flyway owns the schema; Hibernate only validates against it (ddl-auto: validate).

CREATE TABLE pokemon (
    id               BIGINT       PRIMARY KEY,          -- the PokeAPI id
    name             VARCHAR(80)  NOT NULL UNIQUE,
    sprite_url       VARCHAR(255),                       -- US01 small image
    image_url        VARCHAR(255),                       -- US02 official-artwork
    weight           INT,                                -- US01 mass (hectograms; /10 = kg)
    height           INT,
    category         VARCHAR(80),                        -- US01 category (from genera)
    description      TEXT,                               -- US02 narrative description (cleaned)
    hp               INT,
    attack           INT,
    defense          INT,
    special_attack   INT,
    special_defense  INT,
    speed            INT,
    localized_name   VARCHAR(120),                       -- proprietary (US03)
    region           VARCHAR(120),                       -- proprietary (US03)
    internal_tags    VARCHAR(255),                       -- proprietary (US03; CSV)
    created_at       TIMESTAMP,
    updated_at       TIMESTAMP
);

CREATE TABLE pokemon_ability (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pokemon_id   BIGINT       NOT NULL REFERENCES pokemon (id) ON DELETE CASCADE,
    name         VARCHAR(80)  NOT NULL,
    is_hidden    BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_pokemon_ability_pokemon_id ON pokemon_ability (pokemon_id);

CREATE TABLE pokemon_evolution (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pokemon_id    BIGINT       NOT NULL REFERENCES pokemon (id) ON DELETE CASCADE,
    species_name  VARCHAR(80)  NOT NULL,
    stage         INT          NOT NULL                 -- 1,2,3... ordering of the chain
);

CREATE INDEX idx_pokemon_evolution_pokemon_id ON pokemon_evolution (pokemon_id);

CREATE TABLE users (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR(50)  NOT NULL UNIQUE,
    email          VARCHAR(120) NOT NULL UNIQUE,
    password_hash  VARCHAR(255) NOT NULL,
    role           VARCHAR(20)  NOT NULL,               -- USER / ADMIN
    created_at     TIMESTAMP
);
